Translations = { 
    'ru': {
        'level_status' : 'Выберите уровень сложности: easy/normal/hard/impossible:',
        'stat_user' : 'Игрок | Попытки | Время',
        'stat_clue' : "Что бы вывести таблицу рекордов, введите 'stat'",
        'name' : 'Введите ваше имя: ',
        'start' : 'Добро пожаловать в игру, {}!',
        'record_status' : 'Текущий рекорд, который нужно побить: {} попыток.',
        'guess' : 'Введите число от 1 до {}:', 
        'range' : 'Число должно быть в диапазоне от 1 до {}!',
        'higher' : 'Число больше',
        'less' : 'Число меньше!',
        'numbers_only' : 'Введи ЦИФРЫ, бро.',
        'exit' : 'Нажмите Enter для выхода...',
        'attempts_1' : 'WTF! Ты чё Эпштейн? {} попыток даже мне не по зубам.',
        'attempts_7' : 'Браво босс! {} попыток, достойный результат.',
        'attempts_10' : 'Более менее, {} попыток, но все равно поздравляю.',
        'troll_start' : 'Эй чувак! Ты когда тест на IQ проходил ',
        'hood_troll' : 'Это район для крутых, проваливай!',
        'shame' : '{} попыток, позор!',
        'calling' : 'Звоним твоей маме!',
        'mom_answer' : 'Твоя мама: Вы серьезно? Я сейчас откажусь от него.',
        'quote' : 'You can always be thinner. Look Better. - P.Bateman',
        'look' : 'LOOK BETTER',
        'new_record' : 'Отлично, твой новый рекорд на {} попыток лучше.',
        'bad_record' : 'Бро, в прошлый раз ты был лучше. Твой лучший результат был {}.'
        
        },
    'en': {
        'level_status' : 'Select difficulty level: easy/normal/hard/impossible:',
        'stat_user' : 'Users | Attempts | Time',
        'stat_clue' : "To display the high score table, enter 'stat'",
        'name' : 'Enter your name:',
        'start' : 'Welcome to the game, {}!',
        'record_status' : 'Current record to beat: {} attempts.',
        'guess' : 'Enter a number between 1 and {}: ',
        'range' : 'The number must be between 1 and {}!',
        'higher' : 'The number is higher!',
        'less' : 'The number is less!',
        'numbers_only' : 'Enter the NUMBERS, bro.',
        'exit' : 'Press Enter to exit...',
        'attempts_1' : 'WTF! Are you Einstein? Even I can`t guess in {} attempts.',
        'attempts_7' : 'Bravo boss! {} attempts, a worthy result.',
        'attempts_10' : 'More or less, {} attempts, but still congratulations!',
        'troll_start' : 'Hey, dude! When did you get your IQ tested?',
        'hood_troll' : 'This is a cool neighborhood, get lost!',
        'shame' : '{} attempts, shame!',
        'calling' : "We're calling your mom!",
        'mom_answer' : "Your mom: Are you serious? I'll give him up right now.",
        'quote' : 'You can always be thinner. Look Better. - P.Bateman',
        'look' : 'LOOK BETTER',
        'new_record' : 'Cool, Your new record is {} attempts better.',
        'bad_record' : 'Bro, you were better last time. Your best was {}.',
    },
    'uk': {
        'level_status': 'Оберіть рівень складності: easy/normal/hard/impossible:',
        'stat_user': 'Гравець | Спроби | Час',
        'stat_clue': "Щоб вивести таблицю рекордів, введіть 'stat'",
        'name': 'Введіть ваше ім’я: ',
        'start': 'Ласкаво просимо до гри, {}!',
        'record_status': 'Поточний рекорд, який треба побити: {} спроб.',
        'guess': 'Введіть число від 1 до {}:',
        'range': 'Число має бути в діапазоні від 1 до {}!',
        'higher': 'Число більше',
        'less': 'Число менше!',
        'numbers_only': 'Вводь ЦИФРИ, бро.',
        'exit': 'Натисніть Enter для виходу...',
        'attempts_1': 'WTF! Ти що, Эйнштейн? {} спроб навіть мені не по зубах.',
        'attempts_7': 'Браво, бос! {} спроб, гідний результат.',
        'attempts_10': 'Більш-менш, {} спроб, але все одно вітаю.',
        'troll_start': 'Гей, чувак! Ти коли тест на IQ проходив? ',
        'hood_troll': 'Це район для крутих, забирайся звідси!',
        'shame': '{} спроб, ганьба!',
        'calling': 'Дзвонимо твоїй мамі!',
        'mom_answer': 'Твоя мама: Ви серйозно? Я зараз відмовлюся від нього.',
        'quote': 'You can always be thinner. Look Better. - P.Bateman',
        'look': 'LOOK BETTER',
        'new_record': 'Чудово, твій новий рекорд на {} спроб кращий.',
        'bad_record': 'Бро, минулого разу ти був кращим. Твій найкращий результат був {}.'
    },
    'jp': {
        'level_status': '難易度を選択してください (easy/normal/hard/impossible):',
        'stat_user': 'プレイヤー | 試行回数 | 時間',
        'stat_clue': "ランキングを表示するには 'stat' と入力してください",
        'name': '名前を入力してください: ',
        'start': 'ようこそ、{}！',
        'record_status': '現在の記録：{} 回。これを超えてみろ！',
        'guess': '1から {} までの数字を入力してください:',
        'range': '1から {} までの範囲で入力してください！',
        'higher': 'もっと大きい数字です',
        'less': 'もっと小さい数字です！',
        'numbers_only': '数字を入力しろ、ブラザー。',
        'exit': 'Enterを押して終了...',
        'attempts_1': 'なんだって！あれはアインシュタインか？俺が何回やってもあんなことはできないよ。',
        'attempts_7': 'ブラボー、ボス！ {} 回か、見事な結果だ。',
        'attempts_10': 'まあまあだな。 {} 回。とりあえずおめでとう。',
        'troll_start': 'おいおい！IQテストいつ受けたんだ？ ',
        'hood_troll': 'ここはタフな奴らの縄張りだ。失せろ！',
        'shame': '{} 回だと？恥を知れ！',
        'calling': 'お前のママに電話中...',
        'mom_answer': 'ママ：マジで？もうあの子の親やめるわ。',
        'quote': 'You can always be thinner. Look Better. - P.Bateman',
        'look': 'もっと上を目指せ',
        'new_record': 'お見事！自己ベストを {} 回更新したぞ。',
        'bad_record': 'おい、前回の方がマシだったぞ。お前のベストは {} 回だ。'
    },
    'de': {
    'level_status': 'Wähle den Schwierigkeitsgrad: easy/normal/hard/impossible:',
    'stat_user': 'Spieler | Versuche | Zeit',
    'stat_clue': "Gib 'stat' ein, um die Bestenliste anzuzeigen",
    'name': 'Gib deinen Namen ein: ',
    'start': 'Willkommen im Spiel, {}!',
    'record_status': 'Der aktuelle Rekord liegt bei {} Versuchen.',
    'guess': 'Gib eine Zahl zwischen 1 und {} ein:',
    'range': 'Die Zahl muss im Bereich von 1 bis {} liegen!',
    'higher': 'Die Zahl ist größer',
    'less': 'Die Zahl ist kleiner!',
    'numbers_only': 'Gib ZAHLEN ein, Bro.',
    'exit': 'Drücke Enter zum Beenden...',
    'attempts_1': 'WTF! Bist du Einstein? {} Versuche sind selbst für mich zu krass.',
    'attempts_7': 'Bravo Boss! {} Versuche, ein respektables Ergebnis.',
    'attempts_10': 'Ganz okay, {} Versuche, aber trotzdem Glückwunsch.',
    'troll_start': 'Hey Kumpel! Wann hast du eigentlich deinen IQ-Test gemacht? ',
    'hood_troll': 'Das ist das Viertel für die Harten, verschwinde!',
    'shame': '{} Versuche, was für eine Schande!',
    'calling': 'Wir rufen deine Mutter an!',
    'mom_answer': 'Deine Mutter: Ernsthaft? Ich verleugne ihn gleich.',
    'quote': 'You can always be thinner. Look Better. - P.Bateman',
    'look': 'LOOK BETTER',
    'new_record': 'Super, dein neuer Rekord ist um {} Versuche besser.',
    'bad_record': 'Bro, letztes Mal warst du besser. Dein bestes Ergebnis war {}.'
},
'it': {
    'level_status': 'Scegli il livello di difficoltà: easy/normal/hard/impossible:',
    'stat_user': 'Giocatore | Tentativi | Tempo',
    'stat_clue': "Inserisci 'stat' per visualizzare la classifica",
    'name': 'Inserisci il tuo nome: ',
    'start': 'Benvenuto nel gioco, {}!',
    'record_status': 'Il record attuale da battere è di {} tentativi.',
    'guess': 'Inserisci un numero da 1 a {}:',
    'range': 'Il numero deve essere compreso tra 1 e {}!',
    'higher': 'Il numero è più grande',
    'less': 'Il numero è più piccolo!',
    'numbers_only': 'Inserisci dei NUMERI, frate.',
    'exit': 'Premi Invio per uscire...',
    'attempts_1': 'Incredibile! Ma chi sei, Einstein? {} tentativi sono un record pazzesco.',
    'attempts_7': 'Bravo capo! {} tentativi, un risultato degno.',
    'attempts_10': 'Così così, {} tentativi, ma congratulazioni comunque.',
    'troll_start': 'Ehi coso! Ma quando lo hai fatto il test del QI? ',
    'hood_troll': 'Questo è un quartiere per gente tosta, sparisci!',
    'shame': '{} tentativi, che vergogna!',
    'calling': 'Stiamo chiamando tua madre!',
    'mom_answer': 'Tua madre: Dite sul serio? Non ci posso credere.',
    'quote': 'You can always be thinner. Look Better. - P.Bateman',
    'look': 'LOOK BETTER',
    'new_record': 'Ottimo, il tuo nuovo record è migliore di {} tentativi.',
    'bad_record': 'Frate, la scorsa volta eri meglio. Il tuo miglior risultato è stato {}.'
}    

}
